# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/camera

PRODUCT_COPY_FILES += \
    vendor/oneplus/camera/proprietary/product/etc/permissions/com.oneplus.camera.service.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.oneplus.camera.service.xml \
    vendor/oneplus/camera/proprietary/product/etc/permissions/com.oneplus.camera.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.oneplus.camera.xml \
    vendor/oneplus/camera/proprietary/product/etc/permissions/com.oneplus.gallery.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.oneplus.gallery.xml \
    vendor/oneplus/camera/proprietary/product/priv-app/OnePlusCamera/lib/arm64/libsnpe_dsp_v66_domains_v2_skel.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/OnePlusCamera/lib/arm64/libsnpe_dsp_v66_domains_v2_skel.so \
    vendor/oneplus/camera/proprietary/system/etc/sysconfig/hiddenapi-whitelist-oplus.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/hiddenapi-whitelist-oplus.xml

PRODUCT_PACKAGES += \
    OnePlusGallery \
    OnePlusCamera \
    OnePlusCameraPicProcService \
    OnePlusCameraService
